apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-demo
  labels:
    app: rancher-demo
spec:
  selector:
    matchLabels:
      app: rancher-demo
  strategy:
    type: Recreate
  replicas: 2
  template:
    metadata:
      labels:
        app: rancher-demo
    spec:
      containers:
      - image: salahgo/rancher-demo
        name: rancher-demo-container-changed
        ports:
        - containerPort: 80
