apiVersion: v1
kind: Service
metadata:
  name: rancher-demo-service
  labels:
    app: rancher-demo
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: rancher-demo
  type: LoadBalancer
